spring.application.name=airBnbApp
server.port=9091
# DataBase Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=password
# Driver Class (Explicitly adding this helps Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
#
server.servlet.context-path=/api/v1


