spring.application.name=airBnbApp
server.port=9091
# DataBase Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/airBnb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
# Driver Class (Explicitly adding this helps Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
#
server.servlet.context-path=/api/v1
# Spring Security
jwt.secretKey=qpieualkjdhfwkerhoiasdufasdnfkjahsfksajbwebhasbfjsabdfh34284357bdjfb3urhuhdfh7fiusfha7fasuf
#stripe
#storing
frontend.url=http://localhost:5173
stripe.secret.key=sk_test_51TKcZSEtWCXOOLWdin4N84CsYcwUuw2jqDUdg4JR7lzvIDyxpR8SHgdPGIyXjtLU1ZborklSAH0ugxW2wQ07Ehef008ZGKViAK
stripe.webhook.secret=whsec_5487cfa6b342c580a858092c89aaedf6c7b41dd6bc291ae0139a4d57e47d02e2
support.email=support@noxplatform.com
