spring.application.name=airBnbApp
server.port=9091
# DataBase Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=password
# Driver Class (Explicitly adding this helps Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
#
server.servlet.context-path=/api/v1
# Spring Security
jwt.secretKey=qpieualkjdhfwkerhoiasdufasdnfkjahsfksajbwebhasbfjsabdfh34284357bdjfb3urhuhdfh7fiusfha7fasuf
#stripe
#storing
frontend.url=http://localhost:5173
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_placeholder}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_placeholder}
support.email=support@noxplatform.com
